### ISSUE TITLE
Creare il footer

### ISSUE THREAD

**Issue by sebacaccaro** [sebacaccaro/LumBooks#6]
Creare la parte bassa della pagina, che sara' uguale per ogni pagina.
Basta metterla in file HTML nel'apposita cartella, sull'esempio della navbar e dell'header.
Metterci i loghetti fighi, i contatti e robe simili, magari anche un CSS di base. Non spendere troppo tempo sul CSS, perche' piu' avanti ne faremo uno piu' serio

**Comment by linpengzhang** [comment]
Provvedo entro il weekend

**Comment by linpengzhang** [comment]
Ho messo i tasti social
